name: Build macOS
on:
  workflow_dispatch:

  push:
    branches-ignore:
      - main
    paths-ignore:
      - '.github/workflows/release.yaml'
      - '.github/ISSUE_TEMPLATE/**'
      - 'patches-contrib/**'
      - 'LICENSE'
      - '**/*.md'
      - 'README.md'

  pull_request:
    paths-ignore:
      - '.github/workflows/release.yaml'
      - '.github/__release_template.txt'
      - 'patches-contrib/**'
      - 'LICENSE'
      - '**/*.md'
      - 'README.md'

env:
  progname: "magiskboot"

permissions:
  contents: read

jobs:
  vars:
    name: Prepare (variables)
    runs-on: ubuntu-latest
    permissions:
      contents: none
    outputs:
      short_sha: ${{ steps.get_short_sha.outputs.SHORT_SHA }}
      cmake_build_type: ${{ steps.detect_build_type.outputs.CMAKE_BUILD_TYPE }}
      build_type: ${{ steps.detect_build_type.outputs.BUILD_TYPE }}
    steps:
      - name: Determine short Git commit SHA
        id: get_short_sha
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c 1-7`" | tee -a $GITHUB_OUTPUT

      - name: Detect build types
        id: detect_build_type
        run: |
          CMAKE_BUILD_TYPE=Release
          echo "CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}" | tee -a $GITHUB_OUTPUT
          echo "BUILD_TYPE=${CMAKE_BUILD_TYPE,,}" | tee -a $GITHUB_OUTPUT

  src:
    name: Prepare (source)
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --no-install-suggests patch cmake ninja-build

      - name: Prepare (Git)
        run: |
          git config --global user.email "user@example.com"
          git config --global user.name "Example user"

      - name: Prepare (checkout)
        uses: actions/checkout@v4

      - name: Prepare (submodule)
        run: |
          ./scripts/clone_submodules.sh

          for _repo in $(git submodule foreach --recursive --quiet 'env'); do
            git config --global --add safe.directory "$_repo"
          done
          unset _repo

      - name: Package source
        run: |
          CC=true cmake -B build -G Ninja -DCMAKE_C_COMPILER_WORKS=YES -DWITHOUT_BUILD=ON
          cmake --build build -t package_source -v

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: srcpkg
          if-no-files-found: error
          path: ${{ github.workspace }}/build/magiskboot_*-src.tar.xz

  build-macos:
    name: Build (macOS)
    strategy:
      matrix:
        os_release: [15]
    runs-on: macos-${{ matrix.os_release }}
    permissions:
      actions: write
    needs: [vars]
    env:
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1

      upload_suffix: "standalone"

    steps:
      - name: Prepare
        run: |
          brew update
          # HACK: ignore werid symlink conflict
          brew install --overwrite coreutils wget file xz lz4 pkg-config cmake ninja llvm rust || true
          brew install --overwrite coreutils wget file xz lz4 pkg-config cmake ninja llvm rust
          echo "$(brew --prefix)/opt/llvm/bin" | tee -a $GITHUB_PATH

      - name: Prepare (Detect)
        id: detect-runner
        run: |
          echo "uname_mach=$(uname -m)" | tee -a $GITHUB_OUTPUT

      - name: Fix up Rust
        if: matrix.os_release == 15
        run: |
          rm -rf ~/.cargo/registry/index

      - name: Synchronize (source)
        uses: yogeshlonkar/wait-for-jobs@v0.2.1
        with:
          jobs: 'Prepare (source)'

      - name: Prepare (source)
        uses: actions/download-artifact@v4
        with:
          name: srcpkg

      - name: Build
        run: |
          echo -e "\n### extract source ###\n"
          tar -xf magiskboot_*-src.tar.xz

          cd magiskboot_*-src/

          echo -e "\n### configure ###\n"
          CC=clang CXX=clang++ cmake -G Ninja -B build -DCMAKE_AR=llvm-ar -DCMAKE_RANLIB=llvm-ranlib \
              -DCMAKE_BUILD_TYPE=${{ needs.vars.outputs.cmake_build_type }} \
              -DCMAKE_EXE_LINKER_FLAGS=" " \
              -DPREFER_STATIC_LINKING=ON -DFULL_RUST_LTO=OFF

          echo -e "\n### build ###\n"
          cmake --build build -j $(nproc) -v
          strip build/magiskboot*

          file build/magiskboot*
          otool -L build/magiskboot*
          ./build/magiskboot* || true
          rm -rf $GITHUB_WORKSPACE/${{ env.progname }}-out && mkdir -p $GITHUB_WORKSPACE/${{ env.progname }}-out
          cp -afv build/magiskboot* $GITHUB_WORKSPACE/${{ env.progname }}-out

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: ${{ env.progname }}-${{ needs.vars.outputs.short_sha }}-${{ needs.vars.outputs.build_type }}-macos-${{ matrix.os_release }}-${{ steps.detect-runner.outputs.uname_mach }}-${{ env.upload_suffix }}
          path: ${{ github.workspace }}/${{ env.progname }}-out/magiskboot*

      - name: Check
        run: |
          cd magiskboot_*-src/
          ./scripts/magiskboot_test.sh $GITHUB_WORKSPACE/${{ env.progname }}-out/magiskboot*

      # Fail fast
      - name: Cancel other jobs
        if: failure()
        uses: andymckay/cancel-action@0.4

  build-macos-cross:
    name: Build (macOS) (Cross)
    strategy:
      matrix:
        include:
          - os_release: 15
            # yeah crossing x86_64 from arm64 host now...
            arch: "x86_64"
            cmake_arch: "x86_64"
            clang_target: "x86_64-apple-darwin"
            vcpkg_triplet: "x64-osx"
            rust_target: "x86_64-apple-darwin"

    runs-on: macos-${{ matrix.os_release }}
    permissions:
      actions: write
    needs: [vars]
    env:
      HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1

      # only used on ARM64 runners,
      # since there is no preinstalled Vcpkg on them
      vcpkg_ver: 2024.01.12

      upload_suffix: "standalone"

    steps:
      - name: Prepare (Host)
        run: |
          brew update
          # HACK: ignore werid symlink conflict
          brew install --overwrite coreutils file pkg-config cmake ninja llvm || true
          brew install --overwrite coreutils file pkg-config cmake ninja llvm

      - name: Prepare (Detect)
        id: detect-runner
        run: |
          if [[ -z "${VCPKG_INSTALLATION_ROOT}" ]]; then
            echo "has_vcpkg=false" | tee -a $GITHUB_OUTPUT
          else
            echo "has_vcpkg=true" | tee -a $GITHUB_OUTPUT
          fi

      - name: Cache (Vcpkg Bootstrap)
        id: cache-vcpkg-boot
        if: steps.detect-runner.outputs.has_vcpkg != 'true'
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/${{ env.progname }}-vcpkg-strap
          key: vcpkg-${{ env.vcpkg_ver }}-${{ runner.os }}-${{ matrix.os_release }}-${{ runner.arch }}

      - name: Prepare (Vcpkg source)
        if: steps.detect-runner.outputs.has_vcpkg != 'true' && steps.cache-vcpkg-boot.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: microsoft/vcpkg
          ref: ${{ env.vcpkg_ver }}
          path: ${{ env.progname }}-vcpkg-strap

      - name: Prepare (Vcpkg Bootstrap)
        if: steps.detect-runner.outputs.has_vcpkg != 'true' && steps.cache-vcpkg-boot.outputs.cache-hit != 'true'
        run: |
          cd ${{ env.progname }}-vcpkg-strap
          ./bootstrap-vcpkg.sh

      - name: Prepare (Vcpkg)
        if: steps.detect-runner.outputs.has_vcpkg != 'true'
        run: |
          rm -rf $GITHUB_WORKSPACE/${{ env.progname }}-vcpkg/
          cp -af $GITHUB_WORKSPACE/${{ env.progname }}-vcpkg-strap/ \
                 $GITHUB_WORKSPACE/${{ env.progname }}-vcpkg/

          VCPKG_INSTALLATION_ROOT="${GITHUB_WORKSPACE}/${{ env.progname }}-vcpkg"

          echo "${VCPKG_INSTALLATION_ROOT}" | tee -a $GITHUB_PATH
          echo "VCPKG_INSTALLATION_ROOT=${VCPKG_INSTALLATION_ROOT}" | tee -a $GITHUB_ENV

      - name: Prepare (Environment)
        run: |
          echo "vcpkg_root=$VCPKG_INSTALLATION_ROOT" | tee -a $GITHUB_ENV

      - name: Cache (Cross)
        id: cache-cross-vcpkgs
        uses: actions/cache@v4
        with:
          path: ${{ env.vcpkg_root }}/installed
          key: cross-vcpkgs-v2-${{ matrix.vcpkg_triplet }}-appleclang-macos-${{ matrix.os_release }}

      - name: Prepare (Cross)
        run: |
          vcpkg install --host-triplet=${{ matrix.vcpkg_triplet }} liblzma lz4

      - name: Prepare (PATH)
        run: |
          echo "$(brew --prefix)/opt/llvm/bin" | tee -a $GITHUB_PATH

      - name: Prepare (Rust)
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          . "$HOME/.cargo/env"
          rustup target add ${{ matrix.rust_target }}

      - name: Fix up Rust
        if: matrix.os_release == 15
        run: |
          rm -rf ~/.cargo/registry/index

      - name: Synchronize (source)
        uses: yogeshlonkar/wait-for-jobs@v0.2.1
        with:
          jobs: 'Prepare (source)'

      - name: Prepare (source)
        uses: actions/download-artifact@v4
        with:
          name: srcpkg

      - name: Build
        run: |
          echo -e "\n### extract source ###\n"
          tar -xf magiskboot_*-src.tar.xz

          cd magiskboot_*-src/

          echo -e "\n### configure ###\n"
          . "$HOME/.cargo/env"
          CC=clang CXX=clang++ cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=${{ needs.vars.outputs.cmake_build_type }} \
              -DCMAKE_SYSTEM_PROCESSOR=${{ matrix.cmake_arch }} -DCMAKE_SYSTEM_NAME=Darwin \
              -DCMAKE_C_COMPILER_TARGET=${{ matrix.clang_target }} -DCMAKE_CXX_COMPILER_TARGET=${{ matrix.clang_target }} \
              -DCMAKE_AR=llvm-ar -DCMAKE_RANLIB=llvm-ranlib \
              -DCMAKE_EXE_LINKER_FLAGS=" " \
              -DRust_CARGO_TARGET=${{ matrix.rust_target }} -DPREFER_STATIC_LINKING=ON \
              -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake \
              -DVCPKG_TARGET_TRIPLET=${{ matrix.vcpkg_triplet }} \
              -DFULL_RUST_LTO=OFF

          echo -e "\n### build ###\n"
          cmake --build build -j $(nproc) -v
          strip build/magiskboot*

          file build/magiskboot*
          otool -L build/magiskboot*
          rm -rf $GITHUB_WORKSPACE/${{ env.progname }}-out && mkdir -p $GITHUB_WORKSPACE/${{ env.progname }}-out
          cp -afv build/magiskboot* $GITHUB_WORKSPACE/${{ env.progname }}-out

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: ${{ env.progname }}-${{ needs.vars.outputs.short_sha }}-${{ needs.vars.outputs.build_type }}-macos-${{ matrix.os_release }}-${{ matrix.arch }}-${{ env.upload_suffix }}
          path: ${{ github.workspace }}/${{ env.progname }}-out/magiskboot*
